### ISSUE TITLE
Erreur installation package OpenSILEX/opensilexClientR

### ISSUE THREAD

**Issue by XavierDelpuech** [OpenSILEX/opensilexClientR#1]
> library(remotes)
> install_github("OpenSILEX/opensilexClientR", build_vignettes=TRUE, ref="1.0.0")
Downloading GitHub repo OpenSILEX/opensilexClientR@1.0.0
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                            
2: CRAN packages only             
3: None                           
4: stringi (1.5.3 -> 1.6.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
>1
Downloading GitHub repo opensilex/opensilex-ws-client-r@2.2.0
Running `R CMD build`...
* checking for file 'C:\Users\Install\AppData\Local\Temp\Rtmpq8Tz4e\remotes4304492431fd\OpenSILEX-opensilex-ws-client-R-e041293/DESCRIPTION' ... OK
* preparing 'opensilexWSClientR':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building 'OpenSILEXWSConnection.Rmd' using rmarkdown
Error: processing vignette 'OpenSILEXWSConnection.Rmd' failed with diagnostics:
The 'rmarkdown' package should be installed and declared as a dependency of the 'opensilexWSClientR' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
--- failed re-building 'OpenSILEXWSConnection.Rmd'

SUMMARY: processing the following file failed:
  'OpenSILEXWSConnection.Rmd'

Erreur : Vignette re-building failed.
Exécution arrêtée
STDOUT:
* checking for file 'C:\Users\Install\AppData\Local\Temp\Rtmpq8Tz4e\remotes4304492431fd\OpenSILEX-opensilex-ws-client-R-e041293/DESCRIPTION' ... OK
* preparing 'opensilexWSClientR':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
--- re-building 'OpenSILEXWSConnection.Rmd' using rmarkdown
Error: processing vignette 'OpenSILEXWSConnection.Rmd' failed with diagnostics:
The 'rmarkdown' package should be installed and declared as a dependency of the 'opensilexWSClientR' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package. Please see https://github.com/yihui/knitr/issues/1864 for more information.
--- failed re-building 'OpenSILEXWSConnection.Rmd'

SUMMARY: processing the following file failed:
  'OpenSILEXWSConnection.Rmd'

Erreur : Vignette re-building failed.
Exécution arrêtée
STDERR:

**Comment by niio972** [comment]
Could you try to install the "rmarkdown" package with the command line :
```r
 install.packages("rmarkdown")
```
The 'rmarkdown' package should be installed and declared as a dependency of the 'opensilexWSClientR' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package.

**Comment by XavierDelpuech** [comment]
Thanks, this help to go ahead, but a new error occured about "wicket" dependency, see below
(nevertheless, the package "opensilexWSClientR" seems to be installed (but not the one called "opensilexClientR")

Downloading GitHub repo OpenSILEX/opensilexClientR@1.0.0
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                            
2: CRAN packages only             
3: None                           
4: tibble  (3.1.1 -> 3.1.2) [CRAN]
5: stringi (1.5.3 -> 1.6.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
Running `R CMD build`...
* checking for file 'C:\Users\Install\AppData\Local\Temp\Rtmpq8Tz4e\remotes4304346d5084\OpenSILEX-opensilexClientR-ea6f02b/DESCRIPTION' ... OK
* preparing 'opensilexClientR':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'opensilexClientR_1.0.0.tar.gz'
ERROR: dependency 'wicket' is not available for package 'opensilexClientR'
* removing 'C:/Program Files/R/R-4.0.4/library/opensilexClientR'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Install/AppData/Local/Temp/Rtmpq8Tz4e/file430421b434d/opensilexClientR_1.0.0.tar.gz’ had non-zero exit status

**Comment by niio972** [comment]
Thanks for the feedback. It seems that "wicket" dependency has been removed from CRAN repository.

> Package ‘wicket’ was removed from the CRAN repository.
> Formerly available versions can be obtained from the archive.
> Archived on 2021-01-27 as check problems were not corrected in time.
> A summary of the most recent check results can be obtained from the check results archive.
> Please use the canonical form https://CRAN.R-project.org/package=wicket to link to this page. 

I will update the dependencies during the day.

**Comment by niio972** [comment]
The package has been updated. Could you try to install it again ?

**Comment by XavierDelpuech** [comment]
it works ! thanks :)

**Comment by niio972** [comment]
You're welcome.
